mobile_store/urls.py
from django.urls import path

from . import views
from mobile_store import views

from .views import (
    CheckoutView
    )


app_name = 'mobile_store'

urlpatterns = [

    path('', views.homeView, name='index'),
    path('about/', views.about, name='about'),
    path('apple/', views.AppleView.as_view(), name='apple'),
    path('android/', views.AndroidView.as_view(), name='android'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('contacting_us/', views.contacting_us, name='contacting_us'),
    path('reviews/', views.reviews, name='reviews'),
    path('viewreviews/', views.viewreviews, name='viewreviews'),
    path('checkout_page/', CheckoutView.as_view(), name='checkout_page'),
    path('checkout_complete/', views.checkout_complete, name='checkout_complete'),
    path('order_summary/', views.OrderSummaryView.as_view(), name='order_summary'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('add_to_basket/<slug>/', views.add_to_basket, name='add_to_basket'),
    path('remove_from_basket/<slug>/', views.remove_from_basket, name='remove_from_basket'),    
    path('remove_single_item_from_basket/<slug>/', views.remove_single_item_from_basket, name='remove_single_item_from_basket'),
]

rango/urls.py
from django.urls import path
from rango import views


app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
         views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
   # path('register/', views.register, name='register'),
   # path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    #path('logout/', views.user_logout, name='logout'),
    #path('search/', views.search, name='search'),
]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from mobile_store import views

urlpatterns = [
    #path('', views.index, name='index'),
    path('', views.homeView, name='index'),
    path('mobile_store/', include('mobile_store.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mobile_store/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from tango_with_django_project import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.db.models.signals import post_save

# Create your models here.
CATEGORY_CHOICES = (
    ('AP', 'Apple'),
    ('AN', 'Android')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
    
#model for the contact 
class Contact(models.Model):
    NAME_MAX_LENGTH = 128
    FEEDBACK_MAX_LENGTH = 200

    firstname = models.CharField(max_length=NAME_MAX_LENGTH)
    surname = models.CharField(max_length=NAME_MAX_LENGTH)
    email = models.EmailField(blank=True)
    feedback = models.CharField(max_length=FEEDBACK_MAX_LENGTH, blank=True)
    def save(self, *args, **kwargs):
       
        super(Contact, self).save(*args, **kwargs)

class Review(models.Model):
    PHONE_MAX_LENGTH = 100
    REVIEW_MAX_LENGTH = 300
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, default="user")
    phone = models.CharField(max_length=PHONE_MAX_LENGTH)
    review = models.CharField(max_length=REVIEW_MAX_LENGTH, blank=True)
    rating = models.IntegerField(default=0)
    def save(self, *args, **kwargs):
       
        super(Review, self).save(*args, **kwargs)

#model for items 
class Item(models.Model):
    phone_name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default='P')
    brand = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default='AP')
    slug = models.SlugField(default="product")
    description = models.TextField(default="Description unavailable for this product")
    image = models.CharField(default="sale.jpg", max_length=400)   
    
    #gets the static url of the image to use in templates
    def get_static_url(self):
       return settings.STATIC_URL + 'images/' + self.image

    def __str__(self):
        return self.phone_name

    #gets absolute url of item
    def get_absolute_url(self):
        return reverse('mobile_store:product', kwargs={
            'slug':self.slug
        })

    #adds item to basket using add to basket view
    def get_add_to_basket_url(self):
        return reverse('mobile_store:add_to_basket', kwargs={
            'slug':self.slug
        })
    
    #removes item from basket using remove from basket view
    def get_remove_from_basket_url(self):
        return reverse('mobile_store:remove_from_basket', kwargs={
            'slug':self.slug
        })


#model used when someone has item in basket
class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    ordered = models.BooleanField(default=False)
    phone = models.ForeignKey(Item, on_delete = models.CASCADE)
    quantity = models.IntegerField(default=1)
    def __str__(self):
        return f"{self.quantity} of {self.phone.phone_name}"

    #gets price of item multiplied by quantity
    def get_total_phone_price(self):
        return self.quantity * self.phone.price

    #gets discount price of item if it has one
    def get_total_discount_phone_price(self):
        return self.quantity * self.phone.discount_price

    #if item has a discount price it uses that, otherwise it returns the normal price
    def get_final_price(self):
        if self.phone.discount_price:
            return self.get_total_discount_phone_price()
        return self.get_total_phone_price()


#model for an order from a user, can add many items to order
class Order(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    ordered = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField() 
    items = models.ManyToManyField(OrderItem)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    #gets order
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total
    
# model for the billing address of the user including the country field
class BillingAddress(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip=models.CharField(max_length=20)
    
    def __str__(self):
        return self.user.username

        





    




    

mobile_store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from mobile_store.models import Item, Order, OrderItem, Review, BillingAddress
from mobile_store.forms import ContactForm, UserForm, ReviewForm, CheckoutForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime

from django.core.mail import EmailMessage   
from django.template.loader import get_template
from django.core.mail import send_mail  #used to email customer
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.core.paginator import Paginator

#ListView used as showing objects on the html page
class HomeView(ListView):
    model = Item
    paginate_by = 8 #used to show how many phones to show on home page
    template_name = 'mobile_store/index.html'

def homeView(request):
    phones = Item.objects.all()
    searchTerm = ''

    if 'search' in request.GET:
        searchTerm = request.GET['search']
        phones = phones.filter(phone_name__icontains=searchTerm)

    if 'type' in request.GET:
        if request.GET.get('type') == "all":
            phones = Item.objects.all()
        else:
            phones = Item.objects.filter(brand=request.GET.get('type'))


    paginator = Paginator(phones, 8)
    page = request.GET.get('page')
    phones = paginator.get_page(page)

    get_copy = request.GET.copy()
    params = get_copy.pop('page', True) and get_copy.urlencode()

    context_dict = {'phones': phones, 'searchTerm':searchTerm, 'parameters': params}

    return render(request, 'mobile_store/index.html', context=context_dict)


class AppleView(ListView):
    model = Item
    template_name = 'mobile_store/apple.html'
    paginate_by = 4

    #only shows the phones with the category apple    
    def get(self, request):
        context_dict = {}
        cat = "Apple"
        context_dict['item_list'] = Item.objects.filter(brand=cat)
        

        return render(request, 'mobile_store/apple.html', context=context_dict)


class AndroidView(ListView):
    model = Item
    paginate_by = 4
    template_name = 'mobile_store/android.html'

    #only shows the phones with the category android  
    def get(self, request):
        context_dict = {}
        cat = "Android"
        context_dict['item_list'] = Item.objects.filter(brand=cat)

        return render(request, 'mobile_store/android.html',context=context_dict)

#shows the order summary, if user does not have an order, will send a message
class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context_dict = {
                'object':order
            }
            
            return render(self.request, 'mobile_store/order_summary.html', context=context_dict)
        except ObjectDoesNotExist:
            messages.error(self.request, "There is no active order")
            return redirect('/')


#used for showing products
class ItemDetailView(DetailView):
    model = Item
    template_name = 'mobile_store/product.html'

#adds a phone to the basket
@login_required
def add_to_basket(request, slug):
    phone = get_object_or_404(Item, slug=slug)
    order_item,created = OrderItem.objects.get_or_create(phone=phone
    , user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        #check if the order item is in the order
        if order.items.filter(phone__slug=phone.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Quantity of this item has been added")
            return redirect('mobile_store:order_summary')
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to basket")
            
            return redirect('mobile_store:order_summary')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "This item was added to basket")
        return redirect('mobile_store:order_summary')


#removes whole item from basket,even if quantity > 1, gives user alerts
@login_required
def remove_from_basket(request, slug):
    phone = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user, ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        #check if the order item is in the order
        if order.items.filter(phone__slug=phone.slug).exists():
            order_item = OrderItem.objects.filter(
                phone=phone,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from basket")
            return redirect('mobile_store:order_summary')
        else:
        
            messages.info(request, "This item was not in basket")
            return redirect('mobile_store:product', slug=slug)
    else:
   
        messages.info(request, "No current order")
        return redirect('mobile_store:product', slug=slug)

#removes one items quantity from the basket
@login_required
def remove_single_item_from_basket(request, slug):
    phone = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user, ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        #check if the order item is in the order
        if order.items.filter(phone__slug=phone.slug).exists():
            order_item = OrderItem.objects.filter(
                phone=phone,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()

            else:
                order.items.remove(order_item)

            messages.info(request, "Quantity of this item has been decreased")
            return redirect('mobile_store:order_summary')
        else:
        
            messages.info(request, "This item was not in basket")
            return redirect('mobile_store:product', slug=slug)
    else:
   
        messages.info(request, "No current order")
        return redirect('mobile_store:product', slug=slug)

class CheckoutView(View):
    
    def get(self, *args, **kwargs):
        
        form = CheckoutForm()
        context = {
            'form': form 
            }
    
        return render(self.request, 'mobile_store/checkout_page.html', context)
    
    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        
        order = Order.objects.get(user=self.request.user, ordered=False)
        
        
        if form.is_valid():
                
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                same_billing_address = form.cleaned_data.get('same_billing_address')
                save_info = form.cleaned_data.get('save_info')
                payment_option = form.cleaned_data.get('payment_option')
                billing_address = BillingAddress(user=self.request.user, street_address=street_address, apartment_address = apartment_address, 
                country=country, zip=zip)
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                print ("Valid")
            
                return redirect('mobile_store:checkout_complete')
        else:
            messages.warning(self.request, "Checkout Failed")          
            return redirect('mobile_store:checkout_page')

def about(request):
    return render(request, 'mobile_store/about.html')

def checkout_complete(request):
    return render(request, 'mobile_store/checkout_complete.html')



#views for contacting the website, sends automated email back to client
def contact_us(request):
    form = ContactForm        
    context_dict = {}


    form= ContactForm(request.POST or None)
    if form.is_valid():
        
        firstname = request.POST.get('firstname')
        surname = request.POST.get('surname')
        email = request.POST.get('email')
        feedback = request.POST.get('feedback')

        contact = form.save(commit=False)
        contact.firstname = firstname
        contact.surname = surname
        contact.email = email
        contact.feedback = feedback
        contact.save()

        subject = "comment"
        comment= firstname + " with the email, " + email + ", sent the following message:\n\n" + feedback + ". We will get back to your message in due course.\n\n" + "Best wishes from the Mobile Store Team";
        send_mail(subject, comment, 'mobilestoregu@gmail.com', [email])


        context_dict['firstname'] = firstname
        context_dict['surname'] = surname
        context_dict['email'] = email
        context_dict['feedback'] = feedback
        #after it emails customer who gave feedback, takes them to different page
        return render(request, 'mobile_store/contacting_us.html', context=context_dict)

    else:
        context =  {'form': form}
        return render(request, 'mobile_store/contact_us.html', context) 
            
#after user has given feedback, they are thanked for the feedback

templates/mobile_store/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load mobile_store_template_tags %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title_block %} Mobile Store {% endblock %}</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
<style>
  body {
    margin: 0px 0px 0px 0px;
    padding: 0px 0px 20px 0px;
  }
</style>
<header>
  <!-- Navbar -->
  <nav class="navbar absolute-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" target="_blank">
        <strong class="green-text">Mobile Store</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'mobile_store:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'mobile_store:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'mobile_store:contact_us' %}">Contact Us</a>
          </li>
     

          
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'mobile_store:order_summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1">{{ user|basket_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Basket </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'mobile_store:reviews' %}">Add a review
              </a>
          </li>
		           
		      <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'mobile_store:viewreviews' %}">View reviews
              </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/accounts/password/change/">Change Password</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link waves-effect" onclick="LoggedOut()" href="{% url 'auth_logout' %}?next={% url 'mobile_store:index' %}"
              target="_blank">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'registration_register' %}">Register Here</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'auth_login' %}">Login</a>
          </li>
          {% endif %}

        </ul>

        <!-- Right -->

        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a href="#" class="nav-link waves-effect">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link waves-effect">
              <i class="fab fa-twitter"></i>
            </a>
          </li>

        </ul>

      </div>

    </div>
  </nav>
</header>
</head>

<body>

{% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}



{% block body_block %}{% endblock %}
  
    
  


  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Copyright-->
    <div class="footer-copyright py-3">

      <p>&copy; 2020 Mobile Store &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </div>
    <!--/.Copyright-->

  </footer>
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
  <script>
    function LoggedOut(){
            alert("You have been logged out");
            
    }
    </script>
</body>

</html>

templates/mobile_store/index.html
{% extends 'mobile_store/base.html' %}
{% load staticfiles %}



{% block title_block %} 
    Homepage
{% endblock %}


 
{% block body_block %}
<div class="jumbotron p-4">
	<div class="container">
		<h1 class ="jumbotron-heading"> 
			{% if user.is_authenticated %}
				Welcome back {{ user.username }}!
			{% else %}
			Welcome to our Mobile Store! Find your phone!</h1>
			{% endif %}
	</div>
</div>

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url({% static 'images/iphoneXRbrilliant.jpg' %}); background-repeat: no-repeat; background-size: cover; background-position: center ;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Apple</strong>
              </h1>
              <p>
                <strong>Latest iPhone range available for sale. Shop now!</strong>
              </p>
              <a target="_blank" href="{% url 'mobile_store:apple' %}" class="btn btn-outline-white btn-lg">
                Click to Shop
              </a>
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url({% static 'images/androidbb.jpg' %}); background-repeat: no-repeat;background-size: 1300px 400px; background-position: center;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Android</strong>
              </h1>
              <p>
                <strong>With our range from Samsung to Huawei, we will not disappoint</strong>
              </p>
              <a target="_blank" href="{% url 'mobile_store:android' %}" class="btn btn-outline-white btn-lg">
                Click to Shop
              </a>
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url({% static 'images/mobilestore.png' %}); background-repeat: no-repeat; background-position: center; background-size:400px;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Mobile Store</strong>
              </h1>
              <p>
                <strong>We are always happy to help. Feel free to give us any feedback</strong>
              </p>
              <a target="_blank" href="{% url 'mobile_store:contact_us' %}" class="btn btn-outline-white btn-lg">
                Contact Us
              </a>
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
      </div>
      <!--/Third slide-->
    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->



  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark green mdb-color lighten-3 mt-3 mb-5">
        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>
        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="?type=all">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="?type=Apple">Apple</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="?type=Android">Android</a>
            </li>
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search", name="search", value="{{ searchTerm }}">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for phone in phones %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ phone.get_static_url }}" class="card-img-top"
                  alt="Picture of the current phone" height=250 width=auto>
                <a href="{{ phone.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ phone.get_brand_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">{{ phone.phone_name }}
                      <span class="badge badge-pill {{ phone.get_label_display }}-color">BUY</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold green-text">
                  <strong>£
                  {% if phone.discount_price %}
                    {{ phone.discount_price }}
                  {% else %}
                    {{ phone.price }}
                  {% endif %}
                </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if phones.has_previous %}
          <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" href="?page={{ phones.previous_page_number }}&{{ parameters }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ phones.number }}&{{ parameters }}">{{ phones.number }}
              
              <span class="sr-only">(current)</span>
            </a>
          </li>
          
          {% if phones.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ phones.next_page_number }}&{{ parameters }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
{% endblock %}